=== codingOnGithub/hx/xh5/x5-bo-root/modules/x5-bo-core/src/main/resources/xsd/x5-bo-def.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.jee-soft.cn/x5-bo-def"
	xmlns:tns="http://www.jee-soft.cn/x5-bo-def" elementFormDefault="qualified">
	<complexType name="bodef">
		<sequence>
			<element name="name" type="string"></element>
			<element name="cagetory" type="string" minOccurs="0"
				maxOccurs="1">
			</element>
			<element name="mainmodel" type="tns:mainmodel"
				minOccurs="1" maxOccurs="1">
			</element>
			<element name="rules" type="tns:rules" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="datatype" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="submodel" type="tns:submodel" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>

	</complexType>

	<complexType name="attribute">
		<sequence>
			<element name="ruleconfig" type="tns:ruleconfig" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="description" type="string" use="required"></attribute>
		<attribute name="type" type="string" use="required"></attribute>
		<attribute name="default" type="string"></attribute>
		<attribute name="isRequire" type="boolean" default="false"></attribute>
		<attribute name="format" type="string"></attribute>
	</complexType>

	<complexType name="mainmodel">
		<sequence>

			<element name="attribute" type="tns:attribute"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="hasMany" type="tns:hasMany" minOccurs="0"
				maxOccurs="unbounded">
			</element>
			<element name="hasOne" type="tns:hasOne" minOccurs="0"
				maxOccurs="unbounded">
			</element>
			<element name="list" type="tns:list" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="description" type="string"></attribute>
	</complexType>
	
	<complexType name="submodel">
		<sequence>

			<element name="attribute" type="tns:attribute"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="hasMany" type="tns:hasMany" minOccurs="0"
				maxOccurs="unbounded">
			</element>
			<element name="hasOne" type="tns:hasOne" minOccurs="0"
				maxOccurs="unbounded">
			</element>
			<element name="list" type="tns:list" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="description" type="string"></attribute>
	</complexType>

	<element name="bodefcfg" type="tns:bodef"></element>

	<complexType name="hasMany">
		<sequence></sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="rel" type="string" use="required"></attribute>
	</complexType>

	<complexType name="hasOne">
		<sequence>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="rel" type="string" use="required"></attribute>
	</complexType>

	<complexType name="list">
		<sequence>
			<element name="attribute" type="tns:attribute" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="rule">
		<sequence></sequence>
		<attribute name="key" type="string" use="optional"></attribute>
		<attribute name="type" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="format"></enumeration>
					<enumeration value="exclusion"></enumeration>
					<enumeration value="inclusion"></enumeration>
					<enumeration value="reference"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="content" type="string" use="optional"></attribute>
		<attribute name="rel" type="string"></attribute>
		<attribute name="tipinfo" type="string"></attribute>
	</complexType>

	<complexType name="ruleconfig">
		<sequence>
			<element name="rule" type="tns:rule" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="rules">
		<sequence>
			<element name="rule" type="tns:rule" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>
</schema>

=== codingOnGithub/hx/xh5/x5-bo-root/modules/x5-bo-core/src/main/resources/xml/person.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:bodefcfg xmlns:tns="http://www.jee-soft.cn/x5-bo-def"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.jee-soft.cn/x5-bo-def ../xsd/x5-bo-def.xsd ">
	<tns:name>person</tns:name>
	<tns:cagetory>com.hotent.test</tns:cagetory>
	<tns:datatype>json</tns:datatype>
	
	<!-- 公用属性规则 -->
	<tns:rules>
		<tns:rule key="accountRule" type="format" tipinfo="只能是字母、数字和下划线(以字母开头)" content="^[a-z|A-Z][a-z|A-Z|0-9|_]+$"/>
		<tns:rule key="emailRule" type="format" tipinfo="电子邮箱地址格式不正确" content="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"/>
		<tns:rule key="urlRule" type="format" tipinfo="url地址格式不正确" content="[a-zA-z]+://[^\s]*"/>
		<tns:rule key="exceptUrlRule" tipinfo="不能是http://www.jee-soft.cn这个地址" type="exclusion" content="http://www.jee-soft.cn"/>
	</tns:rules>
	
	<!-- 主model(有且仅有一个) -->
	<tns:mainmodel name="person" description="个人信息">
		<tns:attribute name="name" type="string" description="姓名">
			<tns:ruleconfig>
				<!-- 引用公用属性规则 -->
				<tns:rule type="reference" rel="accountRule"/>
				<!-- 私有属性规则 -->
				<tns:rule type="exclusion" tipinfo="不能是admin或者system" content="['admin','system']"/>
			</tns:ruleconfig>
		</tns:attribute>
		<tns:attribute name="sex" type="string" description="性别">
			<tns:ruleconfig>
				<tns:rule type="inclusion" tipinfo="性别只能是男或女" content="['男','女']"/>
			</tns:ruleconfig>
		</tns:attribute>
		<tns:attribute name="born" type="string" description="出生日期"/>
		<tns:list>
			<!-- 列表类型的属性 -->
			<tns:attribute name="formername" type="string" description="曾用名">
				<tns:ruleconfig>
					<tns:rule type="inclusion" tipinfo="姓名只能是李或陈" content="['李','陈']"/>
				</tns:ruleconfig>
			</tns:attribute>
			<tns:attribute name="address" type="string" description="住址"/>
		</tns:list>
		<!-- 有一个类型是detail的personDetail -->
		<tns:hasOne name="personDetail" rel="detail"/>
		<!-- 有多个类型是marydetail的familyDetail -->
		<tns:hasMany name="familyDetail" rel="marydetail"/>
	</tns:mainmodel>
	
	<!-- detail的定义 -->
	<tns:submodel name="detail" description="详细信息">
		<tns:attribute name="nationality" type="string" description="国籍">
			<tns:ruleconfig>
				<!-- 子model中定义的rule其所属defId也是 person -->
				<tns:rule type="inclusion" tipinfo="只能在中国和美国中选择" content="['中国','美国']"/>
			</tns:ruleconfig>
		</tns:attribute>
	</tns:submodel>	
	
	<!-- marydetail的定义 -->
	<tns:submodel name="marydetail" description="我的详细信息" >
		<tns:attribute name="marydetaility" type="string" description="marydetail国籍">
			<tns:ruleconfig>
				<!-- 子model中定义的rule其所属defId也是 person -->
				<tns:rule type="inclusion" tipinfo="只能在中国和美国中选择" content="['中国','美国']"/>
			</tns:ruleconfig>
		</tns:attribute>
		<tns:list>
			<!-- 列表类型的属性 -->
			<tns:attribute name="marydetailname" type="string" description="marydetail曾用名"/>
			<tns:attribute name="marydetailaddress" type="string" description="marydetail住址"/>
		</tns:list>
	</tns:submodel>
</tns:bodefcfg>
