=== codingOnGithub/hx/xh5/x5-base-root/modules/base-service-manager/src/main/resources/service-manager.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ksoft.com/service/manager/config"
	xmlns:tns="http://www.ksoft.com/service/manager/config" elementFormDefault="qualified">

	<element name="servicecfg" type="tns:servicecfg"></element>

	<complexType name="httpservice">
		<attribute name="sn" type="string" use="required"></attribute>
		<attribute name="groupno" type="string" use="required"></attribute>
		<attribute name="servicetype" type="string" use="required"></attribute>
		<attribute name="category" type="string" use="required"></attribute>
		<attribute name="servicename" type="string" use="required"></attribute>
		<attribute name="description" type="string" use="required"></attribute>
		<attribute name="url" type="string" use="required"></attribute>
		<attribute name="createby" type="string" use="required"></attribute>
		<attribute name="updateby" type="string"></attribute>
		<attribute name="createdate" type="string" use="required"></attribute>
		<attribute name="disabled" type="int" use="required"></attribute>
		<attribute name="updatedate" type="string"></attribute>
		<attribute name="remark" type="string" ></attribute>
	</complexType>
	
	<complexType name="webservice">
		<attribute name="sn" type="string" use="required"></attribute>
		<attribute name="groupno" type="string" use="required"></attribute>
		<attribute name="servicetype" type="string" use="required"></attribute>
		<attribute name="category" type="string" use="required"></attribute>
		<attribute name="servicename" type="string" use="required"></attribute>
		<attribute name="description" type="string" use="required"></attribute>
		<attribute name="url" type="string" use="required"></attribute>
		<attribute name="namespace" type="string"></attribute>
		<attribute name="outputparam" type="string" use="required"></attribute>
		<attribute name="createby" type="string" use="required"></attribute>
		<attribute name="updateby" type="string"></attribute>
		<attribute name="createdate" type="string" use="required"></attribute>
		<attribute name="disabled" type="int" use="required"></attribute>
		<attribute name="updatedate" type="string"></attribute>
		<attribute name="remark" type="string" ></attribute>
	</complexType>
	
	<complexType name="servicegroup">
			<attribute name="sn" type="string" use="required"></attribute>
			<attribute name="hostname" type="string" use="required"></attribute>
			<attribute name="port" type="int"></attribute>
			<attribute name="groupno" type="string" use="required"></attribute>
			<attribute name="description" type="string" use="required"></attribute>
			<attribute name="createby" type="string" use="required"></attribute>
			<attribute name="updateby" type="string"></attribute>
			<attribute name="createdate" type="string" use="required"></attribute>
			<attribute name="disabled" type="int" use="required"></attribute>
			<attribute name="updatedate" type="string"></attribute>
			<attribute name="remark" type="string" ></attribute>
	</complexType>

	<complexType name="servicecfg">
		<sequence>
			<element name="httpservices" type="tns:httpservices" minOccurs="0"
				maxOccurs="1"></element>
			<element name="webservices" type="tns:webservices" minOccurs="0" 
			maxOccurs="1"></element>
			<element name="servicegroups" type="tns:servicegroups"
				minOccurs="0" maxOccurs="1">
			</element>
		</sequence>
	</complexType>
	
	<complexType name="httpservices">
		<sequence>
			<element name="httpservice" type="tns:httpservice" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	
	<complexType name="webservices">
		<sequence>
			<element name="webservice" type="tns:webservice" minOccurs="0" 
			maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	
	<complexType name="servicegroups">
		<sequence>
			<element name="servicegroup" type="tns:servicegroup"
				minOccurs="0" maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>
	
</schema>

=== codingOnGithub/hx/xh5/x5-base-root/modules/base-service-manager/src/test/resources/service-manager.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:servicecfg xmlns:tns="http://www.ksoft.com/service/manager/config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ksoft.com/service/manager/config ../../main/resources/service-manager.xsd ">

	<tns:httpservices>
		<tns:httpservice groupno="188-weixin" url="/http/weixin/getoauthtoken"
			category="service" sn="1" servicename="getWxOAuth" disabled="0"
			createdate="2014-01-16 10:30:00" servicetype="http" description="get weixin info"
			createby="1" />
		<tns:httpservice groupno="yun9-weixin" url="/http/weixin/getoauthtoken"
			category="service" sn="2" servicename="getWxOAuth" disabled="0"
			createdate="2014-01-16 10:30:00" servicetype="http" description="get weixin info"
			createby="1" />
		<tns:httpservice groupno="yun9-user" url="/http/cmd/user/findAliasByAliasno"
			category="service" sn="3" servicename="findAliasByAliasno" disabled="0"
			createdate="2014-01-16 10:30:00" servicetype="http" description="get user info"
			createby="1" />
		<tns:httpservice groupno="weixinopen" url="/cgi-bin/groups/get"
			category="service" sn="6" servicename="getGroupInfo" disabled="0"
			createdate="2014-01-16 10:30:00" servicetype="http" description="get group info"
			createby="1" />
	</tns:httpservices>
	
	<tns:webservices>
		<tns:webservice groupno="188-bpm"
			url="/bpmx3/service/ProcessService?wsdl" category="service" sn="4"
			servicename="getTasksByUserId" outputparam="List" disabled="0"
			createdate="2014-01-16 10:30:00" servicetype="ws" description="get task info"
			createby="1" namespace="http://api.webservice.platform.hotent.com/" />
	</tns:webservices>
	
	<tns:servicegroups>
		<tns:servicegroup groupno="yun9-weixin" sn="1" port="10090"
			disabled="0" createdate="2014-01-16 10:30:00" hostname="http://www.yun9.com"
			description="云九微信服务配置" createby="1" />

		<tns:servicegroup groupno="188-weixin" sn="2" port="10090"
			disabled="0" createdate="2014-01-16 10:30:00" hostname="http://192.168.1.188"
			description="188微信服务配置" createby="1" />

		<tns:servicegroup groupno="188-bpm" port="8080" sn="3"
			disabled="0" createdate="2014-01-16 10:30:00" hostname="http://192.168.1.188"
			description="188 bpm服务配置" createby="1" />
		
		<tns:servicegroup groupno="yun9-user" sn="4" port="10088"
			disabled="0" createdate="2014-01-16 10:30:00" hostname="http://www.yun9.com"
			description="188用户服务配置" createby="1" />
			
		<tns:servicegroup groupno="weixinopen" sn="4" port="0"
			disabled="0" createdate="2014-01-16 10:30:00" hostname="https://api.weixin.qq.com"
			description="188用户服务配置" createby="1" />
			
	</tns:servicegroups>
	
	
	
</tns:servicecfg>
